#nelmio_cors:
#    defaults:
#        origin_regex: true
#        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
#        allow_headers: ['Content-Type', 'Authorization']
#        expose_headers: ['Link']
#        max_age: 3600
#    paths:
#        '^/': null
#nelmio_cors:
#    defaults:
#        allow_origin: ['*']  # Or specify your frontend URL here: ['http://localhost:4200']
#        allow_headers: ['content-type', 'authorization']
#        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
#        max_age: 3600
#    paths:
#        '^/':  # Apply these settings to all API paths
#            allow_origin: ['*']  # Or specify your frontend URL here: ['http://localhost:4200']
#            allow_headers: ['content-type', 'authorization']
#            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
#            max_age: 3600
nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['content-type', 'authorization']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
        max_age: 3600
    paths:
        '^/': ~